import re
import unittest

from pipelines import ModoMarketPipeline

class TestExpresionesRegulares(unittest.TestCase):
    def test_marca(self):
        modoMarket = ModoMarketPipeline()
        self.assertEqual(modoMarket.capturar_marca("Shampoo Elvive Reparacion Total 5 200 Ml"), "Elvive")
        self.assertEqual(modoMarket.capturar_marca("Shampoo Plusbelle Fuerza Antioxidante X 1000 Ml"), "Plusbelle")
        self.assertEqual(modoMarket.capturar_marca("Shampoo Elvive Hialuronico H/purificante X 400 Ml"), "Elvive")
        self.assertEqual(modoMarket.capturar_marca("Shampoo Tresemme Ondas Boho X 500 Ml"), "Tresemme")
        self.assertEqual(modoMarket.capturar_marca("SH Pepe"), "?")
        self.assertEqual(modoMarket.capturar_marca("Shampoo Clear Men Anticaspa Contorl Caida X 400 Ml"), "Clear Men")
        self.assertEqual(modoMarket.capturar_marca("Shampoo Sedal Crema Balance Doypack 300 Ml"), "Sedal")
        self.assertEqual(modoMarket.capturar_marca("Shampoo Dove 2 En 1 Fuerza Extrema X 400 Ml"), "Dove")
        self.assertEqual(modoMarket.capturar_marca("Shampoo Sedal Ceramidas 650 Ml"), "Sedal")
        self.assertEqual(modoMarket.capturar_marca("Shampoo Dove Sports Active Fresh X 400 Ml"), "Dove")
        self.assertEqual(modoMarket.capturar_marca("Shampoo Tio Nacho Celulas Madres X 200 Ml"), "Tio Nacho")
        self.assertEqual(modoMarket.capturar_marca("Shampoo Johnsons Baby Cabello Claro X 400 Ml"), "Johnsons")
        self.assertEqual(modoMarket.capturar_marca("Shampoo Elvive Rizos Definidos X 400 Ml"), "Elvive")
        self.assertEqual(modoMarket.capturar_marca("Shampoo Pantene Maxprov Hidratacion Extrema 200ml"), "Pantene")
        self.assertEqual(modoMarket.capturar_marca("Shampoo Sedal Liso Perfecto 340 Ml"), "Sedal")
        self.assertEqual(modoMarket.capturar_marca("Shampoo Head & Shoulders Hidratacion X 180 Ml"), "Head & Shoulders")
        
        self.assertEqual(modoMarket.capturar_marca("Coca Cola Sin Azucar X 1.5 Lt"), "Coca Cola")
        self.assertEqual(modoMarket.capturar_marca("Sprite X 1.5 Lt"), "Sprite")
        self.assertEqual(modoMarket.capturar_marca("Coca Cola Botella X 500 Ml"), "Coca Cola")
        self.assertEqual(modoMarket.capturar_marca("Gaseosa Yaci Iguazu Limon Y Jengibre X 354 Cc"), "Yaci")
        self.assertEqual(modoMarket.capturar_marca("Fanta Naranja X 1.5 Lt"), "Fanta")
        self.assertEqual(modoMarket.capturar_marca("Schweppes Tonica X 1.5 Lt"), "Schweppes")
        self.assertEqual(modoMarket.capturar_marca("Leche Tregar Descremada Caja X 1 Lt"), "Tregar")
        self.assertEqual(modoMarket.capturar_marca("Leche La Serenisima Descremada 1 % Botella 1 Lt"), "La Serenisima")
        self.assertEqual(modoMarket.capturar_marca("Leche Serenisima Descremada 1% Caja X 1 L"), "Serenisima")
        self.assertEqual(modoMarket.capturar_marca("Leche Serenisima Entera 3% Caja 1l"), "Serenisima")
        self.assertEqual(modoMarket.capturar_marca("Leche Veronica Larga Vida 1 Lt Descremada"), "Veronica")
        self.assertEqual(modoMarket.capturar_marca("Leche Ilolay Larga Vida Entera X 1 Lt"), "Ilolay")
        self.assertEqual(modoMarket.capturar_marca("Pan Artesano Bimbo X 500 Gr"), "Bimbo")
        self.assertEqual(modoMarket.capturar_marca("Arroz Gallo Risotto 4 Quesos Caja X 240 Gr"), "Gallo")
        self.assertEqual(modoMarket.capturar_marca("Arroz Gallo Mix De Vegetales Bajo En Sodio X 240 G"), "Gallo")
        self.assertEqual(modoMarket.capturar_marca("Arroz Gallo Preparado Queso X 240 Gr"), "Gallo")
        self.assertEqual(modoMarket.capturar_marca("Arroz Gallo Risotto Champiñones X 240 Gr"), "Gallo")
        self.assertEqual(modoMarket.capturar_marca("Arroz Gallo Risotto Española Caja X 240 Gr"), "Gallo")
        self.assertEqual(modoMarket.capturar_marca("Jabon Lux Jazmin Cremoso 3 X 125 Gr"), "Lux")
        self.assertEqual(modoMarket.capturar_marca("Jabon De Glicerina Rexona Neutro 3 X 90 G"), "Rexona")
        self.assertEqual(modoMarket.capturar_marca("Jabon Lux Orquidea Negra X 125 G"), "Lux")
        self.assertEqual(modoMarket.capturar_marca("Jabon Dove Cuida Y Protege X 90 Gr"), "Dove")
        self.assertEqual(modoMarket.capturar_marca("Jabon De Glicerina Rexona Citrus 3 X 90 G"), "Rexona")
        self.assertEqual(modoMarket.capturar_marca("Jabon Plusbelle Humectacion Cremosa 3 X 125 Gr"), "Plusbelle")
        self.assertEqual(modoMarket.capturar_marca("Jabon Plusbelle 3 X 125 Frescura Intensa"), "Plusbelle")
        self.assertEqual(modoMarket.capturar_marca("Jabon Rexona Xtracool 3 X 125 G"), "Rexona")
        self.assertEqual(modoMarket.capturar_marca("Jabon Campos Verdes Energia 120 Gr"), "Campos Verdes")
        self.assertEqual(modoMarket.capturar_marca("Jab.campos Verdes 3 X 120 G Energia"), "campos Verdes")
        self.assertEqual(modoMarket.capturar_marca("Jabon Nivea Antibacterial Aloe Vera 3 X 90 G"), "Nivea")
        self.assertEqual(modoMarket.capturar_marca("Jabon Plusbelle Relajacion 3 X 125 Gr"), "Plusbelle")
        self.assertEqual(modoMarket.capturar_marca("Yerba La Tranquera Suave Seleccion Especial 500 Gr"), "La Tranquera")
        self.assertEqual(modoMarket.capturar_marca("Yerba Playadito X 1 Kg"), "Playadito")
        self.assertEqual(modoMarket.capturar_marca("Yerba Chamigo X 1 Kg"), "Chamigo")
        self.assertEqual(modoMarket.capturar_marca("Yerba Cruz De Malta Boldo Y Menta X 500gr"), "Cruz De Malta")
        self.assertEqual(modoMarket.capturar_marca("Yerba Union Suave C/palo 500 Gr Original 4 Flex"), "Union")
        self.assertEqual(modoMarket.capturar_marca("Yerba Taragui Envase 4 Flex Sin Palo Azul X 500 Gr"), "Taragui")
        self.assertEqual(modoMarket.capturar_marca("Yerba Cruz Malta X 500 Gr Con Palo Nuevo Envase"), "Cruz Malta")
        self.assertEqual(modoMarket.capturar_marca("Yerba Cbse Etiqueta Negra X 500 Gr"), "Cbse")
        self.assertEqual(modoMarket.capturar_marca("Fideos Terrabusi Spaghetti X 500 Gr"), "Terrabusi")
        self.assertEqual(modoMarket.capturar_marca("Fideos Terrabusi Coditos X 500 G"), "Terrabusi")
        self.assertEqual(modoMarket.capturar_marca("Fideos Matarazzo 3 Vegetales Tirabuzon X 500 Gr"), "Matarazzo")
        self.assertEqual(modoMarket.capturar_marca("Fideos Lucchetti Spaghetti N°5 X 500 G"), "Lucchetti")
        self.assertEqual(modoMarket.capturar_marca("Fideos Terrabusi Mix Vegetal Mostachol X 500 G"), "Terrabusi")
        self.assertEqual(modoMarket.capturar_marca("Fideos Matarazzo Tallarin N°7 X 500 Gr"), "Matarazzo")
        self.assertEqual(modoMarket.capturar_marca("Fideos Matarazzo Spaghetti L/gluten X 500 G"), "Matarazzo")
    

    def test_descripcion(self):
        modoMarket = ModoMarketPipeline()
        self.assertEqual(modoMarket.capturar_descripcion("Shampoo Elvive Reparacion Total 5 200 Ml"), "Reparacion Total 5")
        self.assertEqual(modoMarket.capturar_descripcion("Shampoo Plusbelle Fuerza Antioxidante X 1000 Ml"), "Fuerza Antioxidante")
        self.assertEqual(modoMarket.capturar_descripcion("Shampoo Elvive Hialuronico H/purificante X 400 Ml"), "Hialuronico H/purificante")
        self.assertEqual(modoMarket.capturar_descripcion("Shampoo Tresemme Ondas Boho X 500 Ml"), "Ondas Boho")
        self.assertEqual(modoMarket.capturar_descripcion("Shampoo Clear Men Anticaspa Contorl Caida X 400 Ml"), "Anticaspa Contorl Caida")
        self.assertEqual(modoMarket.capturar_descripcion("Shampoo Sedal Crema Balance Doypack 300 Ml"), "Crema Balance Doypack")
        self.assertEqual(modoMarket.capturar_descripcion("Shampoo Dove 2 En 1 Fuerza Extrema X 400 Ml"), "2 En 1 Fuerza Extrema")
        self.assertEqual(modoMarket.capturar_descripcion("Shampoo Sedal Ceramidas 650 Ml"), "Ceramidas")
        self.assertEqual(modoMarket.capturar_descripcion("Shampoo Dove Sports Active Fresh X 400 Ml"), "Sports Active Fresh")
        self.assertEqual(modoMarket.capturar_descripcion("Shampoo Tio Nacho Celulas Madres X 200 Ml"), "Celulas Madres")
        self.assertEqual(modoMarket.capturar_descripcion("Shampoo Johnsons Baby Cabello Claro X 400 Ml"), "Baby Cabello Claro")
        self.assertEqual(modoMarket.capturar_descripcion("Shampoo Elvive Rizos Definidos X 400 Ml"), "Rizos Definidos")
        self.assertEqual(modoMarket.capturar_descripcion("Shampoo Pantene Maxprov Hidratacion Extrema 200ml"), "Maxprov Hidratacion Extrema")
        self.assertEqual(modoMarket.capturar_descripcion("Shampoo Sedal Liso Perfecto 340 Ml"), "Liso Perfecto")
        self.assertEqual(modoMarket.capturar_descripcion("Clear Shampoo Dual Effect 2 En 1 X 400 Ml"), "Dual Effect 2 En 1")
        
        self.assertEqual(modoMarket.capturar_descripcion("Coca Cola Sin Azucar X 1.5 Lt"), "Sin Azucar")
        self.assertEqual(modoMarket.capturar_descripcion("Sprite X 1.5 Lt"), "")
        self.assertEqual(modoMarket.capturar_descripcion("Sprite"), "?")
        self.assertEqual(modoMarket.capturar_descripcion("Coca Cola Botella X 500 Ml"), "Botella")
        self.assertEqual(modoMarket.capturar_descripcion("Gaseosa Yaci Iguazu Limon Y Jengibre X 354 Cc"), "Iguazu Limon Y Jengibre")
        self.assertEqual(modoMarket.capturar_descripcion("Fanta Naranja X 1.5 Lt"), "Naranja")
        self.assertEqual(modoMarket.capturar_descripcion("Schweppes Tonica X 1.5 Lt"), "Tonica")
        self.assertEqual(modoMarket.capturar_descripcion("Leche Tregar Descremada Caja X 1 Lt"), "Descremada Caja")
        self.assertEqual(modoMarket.capturar_descripcion("Leche La Serenisima Descremada 1 % Botella 1 Lt"), "Descremada 1 % Botella")
        self.assertEqual(modoMarket.capturar_descripcion("Leche Serenisima Descremada 1% Caja X 1 L"), "Descremada 1% Caja")
        self.assertEqual(modoMarket.capturar_descripcion("Leche Serenisima Entera 3% Caja 1l"), "Entera 3% Caja")
        self.assertEqual(modoMarket.capturar_descripcion("Leche Veronica Larga Vida 1 Lt Descremada"), "Larga Vida Descremada")
        self.assertEqual(modoMarket.capturar_descripcion("Leche Ilolay Larga Vida Entera X 1 Lt"), "Larga Vida Entera")
        self.assertEqual(modoMarket.capturar_descripcion("Leche Angelita L.vida Entera X 1 Lt"), "L.vida Entera")
        self.assertEqual(modoMarket.capturar_descripcion("Leche Las Tres Niñas X 1 Lt Entera Larga Vida"), "Entera Larga Vida")
        self.assertEqual(modoMarket.capturar_descripcion("Pan Artesano Bimbo X 500 Gr"), "Artesano")
        self.assertEqual(modoMarket.capturar_descripcion("Arroz Gallo Risotto 4 Quesos Caja X 240 Gr"), "Risotto 4 Quesos Caja")
        self.assertEqual(modoMarket.capturar_descripcion("Arroz Gallo Mix De Vegetales Bajo En Sodio X 240 G"), "Mix De Vegetales Bajo En Sodio")
        self.assertEqual(modoMarket.capturar_descripcion("Arroz Gallo Preparado Queso X 240 Gr"), "Preparado Queso")
        self.assertEqual(modoMarket.capturar_descripcion("Arroz Gallo Risotto Champiñones X 240 Gr"), "Risotto Champiñones")
        self.assertEqual(modoMarket.capturar_descripcion("Arroz Gallo Risotto Española Caja X 240 Gr"), "Risotto Española Caja")
        self.assertEqual(modoMarket.capturar_descripcion("Arroz Gallo Preparado Mix De Vegetales X 240 Grs"), "Preparado Mix De Vegetales")
        self.assertEqual(modoMarket.capturar_descripcion("Arroz Topador Largo Fino X 500 Gr"), "Largo Fino")
        self.assertEqual(modoMarket.capturar_descripcion("Arroz Primor Largo Fino 00000 X 1 Kg"), "Largo Fino 00000")
        self.assertEqual(modoMarket.capturar_descripcion("Jabon Lux Jazmin Cremoso 3 X 125 Gr"), "Jazmin Cremoso 3")
        self.assertEqual(modoMarket.capturar_descripcion("Jabon De Glicerina Rexona Neutro 3 X 90 G"), "De Glicerina Neutro 3")
        self.assertEqual(modoMarket.capturar_descripcion("Jabon Lux Orquidea Negra X 125 G"), "Orquidea Negra")
        self.assertEqual(modoMarket.capturar_descripcion("Jabon Dove Cuida Y Protege X 90 Gr"), "Cuida Y Protege")
        self.assertEqual(modoMarket.capturar_descripcion("Jabon De Glicerina Rexona Citrus 3 X 90 G"), "De Glicerina Citrus 3")
        self.assertEqual(modoMarket.capturar_descripcion("Jabon Plusbelle Humectacion Cremosa 3 X 125 Gr"), "Humectacion Cremosa 3")
        self.assertEqual(modoMarket.capturar_descripcion("Jabon Plusbelle 3 X 125 Frescura Intensa"), "3 Frescura Intensa")
        self.assertEqual(modoMarket.capturar_descripcion("Jabon Rexona Xtracool 3 X 125 G"), "Xtracool 3")
        self.assertEqual(modoMarket.capturar_descripcion("Jabon Campos Verdes Energia 120 Gr"), "Energia")
        self.assertEqual(modoMarket.capturar_descripcion("Jab.campos Verdes 3 X 120 G Energia"), "3 Energia")
        self.assertEqual(modoMarket.capturar_descripcion("Jabon Nivea Antibacterial Aloe Vera 3 X 90 G"), "Antibacterial Aloe Vera 3")
        self.assertEqual(modoMarket.capturar_descripcion("Jabon Plusbelle Relajacion 3 X 125 Gr"), "Relajacion 3")
        self.assertEqual(modoMarket.capturar_descripcion("Yerba La Tranquera Suave Seleccion Especial 500 Gr"), "Suave Seleccion Especial")
        self.assertEqual(modoMarket.capturar_descripcion("Yerba Playadito X 1 Kg"), "")
        self.assertEqual(modoMarket.capturar_descripcion("Yerba Chamigo X 1 Kg"), "")
        self.assertEqual(modoMarket.capturar_descripcion("Yerba Cruz De Malta Boldo Y Menta X 500gr"), "Boldo Y Menta")
        self.assertEqual(modoMarket.capturar_descripcion("Yerba Union Suave C/palo 500 Gr Original 4 Flex"), "Suave C/palo Original 4 Flex")
        self.assertEqual(modoMarket.capturar_descripcion("Yerba Taragui Envase 4 Flex Sin Palo Azul X 500 Gr"), "Envase 4 Flex Sin Palo Azul")
        self.assertEqual(modoMarket.capturar_descripcion("Yerba Cruz Malta X 500 Gr Con Palo Nuevo Envase"), "Con Palo Nuevo Envase")
        self.assertEqual(modoMarket.capturar_descripcion("Yerba Canarias X 500 G"), "")
        self.assertEqual(modoMarket.capturar_descripcion("Hierba Cachamate Naranja X 500 G"), "Naranja")
        self.assertEqual(modoMarket.capturar_descripcion("Yerba Cbse Hierbas Serranas X 1 Kg"), "Hierbas Serranas")
        self.assertEqual(modoMarket.capturar_descripcion("Yerba Cbse Etiqueta Negra X 500 Gr"), "Etiqueta Negra")
        self.assertEqual(modoMarket.capturar_descripcion("Fideos Terrabusi Spaghetti X 500 Gr"), "Spaghetti")
        self.assertEqual(modoMarket.capturar_descripcion("Fideos Terrabusi Coditos X 500 G"), "Coditos")
        self.assertEqual(modoMarket.capturar_descripcion("Fideos Matarazzo 3 Vegetales Tirabuzon X 500 Gr"), "3 Vegetales Tirabuzon")
        self.assertEqual(modoMarket.capturar_descripcion("Fideos Lucchetti Spaghetti N°5 X 500 G"), "Spaghetti N°5")
        self.assertEqual(modoMarket.capturar_descripcion("Fideos Terrabusi Mix Vegetal Mostachol X 500 G"), "Mix Vegetal Mostachol")
        self.assertEqual(modoMarket.capturar_descripcion("Fideos Matarazzo Tallarin N°7 X 500 Gr"), "Tallarin N°7")
        self.assertEqual(modoMarket.capturar_descripcion("Fideos Matarazzo Spaghetti L/gluten X 500 G"), "Spaghetti L/gluten")
        self.assertEqual(modoMarket.capturar_descripcion("Fideos Arcor Codito X 500 G"), "Codito")
        self.assertEqual(modoMarket.capturar_descripcion("Fideos Caseritos Marvese Multivegetal X 400 G"), "Marvese Multivegetal")
        self.assertEqual(modoMarket.capturar_descripcion("Fideos Caseritos De Morron X 400 G"), "De Morron")
        self.assertEqual(modoMarket.capturar_descripcion("Fideos Caseritos Marvese De Espinaca X 400 G"), "Marvese De Espinaca")
        self.assertEqual(modoMarket.capturar_descripcion("Fideos Caseritos Marvese Al Huevo X400 G"), "Marvese Al Huevo")
        
    
    def test_volumen(self):
        modoMarket = ModoMarketPipeline()
        self.assertEqual(modoMarket.capturar_volumen("Shampoo Elvive Reparacion Total 5 200 Ml"), "200")
        self.assertEqual(modoMarket.capturar_volumen("Shampoo Plusbelle Fuerza Antioxidante X 1000 Ml"), "1000")
        self.assertEqual(modoMarket.capturar_volumen("Shampoo Elvive Hialuronico H/purificante X 400 Ml"), "400")
        self.assertEqual(modoMarket.capturar_volumen("Shampoo Tresemme Ondas Boho X 500 Ml"), "500")
        self.assertEqual(modoMarket.capturar_volumen("Shampoo Clear Men Anticaspa Contorl Caida X 400 Ml"), "400")
        self.assertEqual(modoMarket.capturar_volumen("Shampoo Sedal Crema Balance Doypack 300 Ml"), "300")
        self.assertEqual(modoMarket.capturar_volumen("Shampoo Dove 2 En 1 Fuerza Extrema X 400 Ml"), "400")
        self.assertEqual(modoMarket.capturar_volumen("Shampoo Sedal Ceramidas 650 Ml"), "650")
        self.assertEqual(modoMarket.capturar_volumen("Shampoo Dove Sports Active Fresh X 400 Ml"), "400")
        self.assertEqual(modoMarket.capturar_volumen("Shampoo Tio Nacho Celulas Madres X 200 Ml"), "200")
        self.assertEqual(modoMarket.capturar_volumen("Shampoo Johnsons Baby Cabello Claro X 400 Ml"), "400")
        self.assertEqual(modoMarket.capturar_volumen("Shampoo Elvive Rizos Definidos X 400 Ml"), "400")
        self.assertEqual(modoMarket.capturar_volumen("Shampoo Pantene Maxprov Hidratacion Extrema 200ml"), "200")
        self.assertEqual(modoMarket.capturar_volumen("Shampoo Sedal Liso Perfecto 340 Ml"), "340")
        self.assertEqual(modoMarket.capturar_volumen("Coca Cola Sin Azucar X 1.5 Lt"), "1500")
        self.assertEqual(modoMarket.capturar_volumen("Sprite X 1.5 Lt"), "1500")
        self.assertEqual(modoMarket.capturar_volumen("Coca Cola Botella X 500 Ml"), "500")
        self.assertEqual(modoMarket.capturar_volumen("Gaseosa Yaci Iguazu Limon Y Jengibre X 354 Cc"), "354")
        self.assertEqual(modoMarket.capturar_volumen("Fanta Naranja X 1.5 Lt"), "1500")
        self.assertEqual(modoMarket.capturar_volumen("Schweppes Tonica X 1.5 Lt"), "1500")
        self.assertEqual(modoMarket.capturar_volumen("Leche Tregar Descremada Caja X 1 Lt"), "1000")
        self.assertEqual(modoMarket.capturar_volumen("Leche La Serenisima Descremada 1 % Botella 1 Lt"), "1000")
        self.assertEqual(modoMarket.capturar_volumen("Leche Serenisima Descremada 1% Caja X 1 L"), "1000")
        self.assertEqual(modoMarket.capturar_volumen("Leche Serenisima Entera 3% Caja 1l"), "1000")
        self.assertEqual(modoMarket.capturar_volumen("Leche Veronica Larga Vida 1 Lt Descremada"), "1000")
        self.assertEqual(modoMarket.capturar_volumen("Leche Ilolay Larga Vida Entera X 1 Lt"), "1000")
        self.assertEqual(modoMarket.capturar_volumen("Pan Artesano Bimbo X 500 Gr"), "500")
        self.assertEqual(modoMarket.capturar_volumen("Arroz Gallo Risotto 4 Quesos Caja X 240 Gr"), "240")
        self.assertEqual(modoMarket.capturar_volumen("Arroz Gallo Mix De Vegetales Bajo En Sodio X 240 G"), "240")
        self.assertEqual(modoMarket.capturar_volumen("Arroz Gallo Preparado Queso X 240 Gr"), "240")
        self.assertEqual(modoMarket.capturar_volumen("Arroz Gallo Risotto Champiñones X 240 Gr"), "240")
        self.assertEqual(modoMarket.capturar_volumen("Arroz Gallo Risotto Española Caja X 240 Gr"), "240")
        self.assertEqual(modoMarket.capturar_volumen("Arroz Gallo Preparado Mix De Vegetales X 240 Grs"), "240")
        self.assertEqual(modoMarket.capturar_volumen("Jabon Lux Jazmin Cremoso 3 X 125 Gr"), "125")
        self.assertEqual(modoMarket.capturar_volumen("Jabon De Glicerina Rexona Neutro 3 X 90 G"), "90")
        self.assertEqual(modoMarket.capturar_volumen("Jabon Lux Orquidea Negra X 125 G"), "125")
        self.assertEqual(modoMarket.capturar_volumen("Jabon Dove Cuida Y Protege X 90 Gr"), "90")
        self.assertEqual(modoMarket.capturar_volumen("Jabon De Glicerina Rexona Citrus 3 X 90 G"), "90")
        self.assertEqual(modoMarket.capturar_volumen("Jabon Plusbelle Humectacion Cremosa 3 X 125 Gr"), "125")
        self.assertEqual(modoMarket.capturar_volumen("Jabon Plusbelle 3 X 125 Frescura Intensa"), "125")
        self.assertEqual(modoMarket.capturar_volumen("Jabon Rexona Xtracool 3 X 125 G"), "125")
        self.assertEqual(modoMarket.capturar_volumen("Jabon Campos Verdes Energia 120 Gr"), "120")
        self.assertEqual(modoMarket.capturar_volumen("Jab.campos Verdes 3 X 120 G Energia"), "120")
        self.assertEqual(modoMarket.capturar_volumen("Jabon Nivea Antibacterial Aloe Vera 3 X 90 G"), "90")
        self.assertEqual(modoMarket.capturar_volumen("Jabon Plusbelle Relajacion 3 X 125 Gr"), "125")
        self.assertEqual(modoMarket.capturar_volumen("Yerba La Tranquera Suave Seleccion Especial 500 Gr"), "500")
        self.assertEqual(modoMarket.capturar_volumen("Yerba Playadito X 1 Kg"), "1000")
        self.assertEqual(modoMarket.capturar_volumen("Yerba Chamigo X 1 Kg"), "1000")
        self.assertEqual(modoMarket.capturar_volumen("Yerba Cruz De Malta Boldo Y Menta X 500gr"), "500")
        self.assertEqual(modoMarket.capturar_volumen("Yerba Union Suave C/palo 500 Gr Original 4 Flex"), "500")
        self.assertEqual(modoMarket.capturar_volumen("Yerba Taragui Envase 4 Flex Sin Palo Azul X 500 Gr"), "500")
        self.assertEqual(modoMarket.capturar_volumen("Yerba Cruz Malta X 500 Gr Con Palo Nuevo Envase"), "500")
        self.assertEqual(modoMarket.capturar_volumen("Yerba Cbse Etiqueta Negra X 500 Gr"), "500")
        self.assertEqual(modoMarket.capturar_volumen("Fideos Terrabusi Spaghetti X 500 Gr"), "500")
        self.assertEqual(modoMarket.capturar_volumen("Fideos Terrabusi Coditos X 500 G"), "500")
        self.assertEqual(modoMarket.capturar_volumen("Fideos Matarazzo 3 Vegetales Tirabuzon X 500 Gr"), "500")
        self.assertEqual(modoMarket.capturar_volumen("Fideos Lucchetti Spaghetti N°5 X 500 G"), "500")
        self.assertEqual(modoMarket.capturar_volumen("Fideos Terrabusi Mix Vegetal Mostachol X 500 G"), "500")
        self.assertEqual(modoMarket.capturar_volumen("Fideos Matarazzo Tallarin N°7 X 500 Gr"), "500")
        self.assertEqual(modoMarket.capturar_volumen("Fideos Matarazzo Spaghetti L/gluten X 500 G"), "500")
        self.assertEqual(modoMarket.capturar_volumen("Fideos Caseritos Marvese Multivegetal X 400 G"), "400")
        self.assertEqual(modoMarket.capturar_volumen("Fideos Caseritos De Morron X 400 G"), "400")
        self.assertEqual(modoMarket.capturar_volumen("Fideos Caseritos Marvese De Espinaca X 400 G"), "400")
        self.assertEqual(modoMarket.capturar_volumen("Fideos Caseritos Marvese Al Huevo X400 G"), "400")
        self.assertEqual(modoMarket.capturar_volumen("Fideos Caseritos Marvese Al Huevo X400 G"), "400")

        self.assertEqual(modoMarket.capturar_volumen('Pan Artesano Bimbo Masa Madre X 500g'), "500")
        # self.assertEqual(modoMarket.capturar_volumen('Yerba Verdeflor Serranasx500gr'), "500")
        self.assertEqual(modoMarket.capturar_volumen('Arroz Dos Hermanos Parboil Bolsa 1 K'), "1000")
        self.assertEqual(modoMarket.capturar_volumen('Coca Cola Lata X 354cc'), "354")
        self.assertEqual(modoMarket.capturar_volumen('Leche Entera 3% Serenisima Sachet 1lt'), "1000")
        self.assertEqual(modoMarket.capturar_volumen('Fideos San Agustin Nido Ancho X 500g'), "500")
        self.assertEqual(modoMarket.capturar_volumen('Fideos Lucchetti Penne Rigate 500g'), "500")
        self.assertEqual(modoMarket.capturar_volumen('Fideos Laminados Premium Robles Al Huevo X 400g'), "400")
        self.assertEqual(modoMarket.capturar_volumen('Fideos Laminados Premium Robles Morron X 400g'), "400")
        self.assertEqual(modoMarket.capturar_volumen('Fideos San Agustin Rigatti X 500g'), "500")
        # self.assertEqual(modoMarket.capturar_volumen('Shampoo Head & Shoulders Limpieza Renovadora X 375'), "375")
        self.assertEqual(modoMarket.capturar_volumen('Yerba Cachamate Hierbas Serranas X 500g'), "500")
        self.assertEqual(modoMarket.capturar_volumen('Yerba Playadito Lata X 500g'), "500")
        self.assertEqual(modoMarket.capturar_volumen('Fideos Laminados Premium Robles Espinaca X 400g'), "400")
        self.assertEqual(modoMarket.capturar_volumen('Fideos Robles Don Salvador Al Huevo Fino X500g'), "500")
        # self.assertEqual(modoMarket.capturar_volumen('Tonica Secco X 2.25 Lts'), "2250")
        self.assertEqual(modoMarket.capturar_volumen('Sprite Lata X 354cc'), "354")



if __name__ == '__main__':
    unittest.main()
