#T* Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: martingreyes/tif-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: backendUrl
          value: "http://127.0.0.1:5001" 
---
#T* ConfigMap
---
#T* Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer 
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80


