#T* Backend Secret 
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  DB_PASSWORD: cm9vdA== 
---
#T* Cronjob Secret
apiVersion: v1
kind: Secret
metadata:
  name: cronjob-secret
  namespace: martingreyes-tif
type: Opaque
stringData:
  DB_USER: root
  DB_PASSWORD: root
  API_KEYS: >-
    AIzaSyB3rhdiwSZLNE1WNT7myNa9Oqy_EmdsRiI,
    AIzaSyAb3p4hG6SfFohZb0Lusq6aIdBqwh6vpjs,
    AIzaSyDUHiTi4t8t8NTzZHlpAX38COlWE0Wr_c0
---
#T* MariaDB Secret
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  root-password: cm9vdA==