import re
import unittest

from pipelines import SuperaPipeline

class TestExpresionesRegulares(unittest.TestCase):
    def test_marca(self):
        supera = SuperaPipeline()
        self.assertEqual(supera.capturar_marca("SH DOVE CUIDA Y PROTEGE X400ML"), "DOVE")
        self.assertEqual(supera.capturar_marca("SH PANTENE HIDRATACION EXTREMA 200 ML"), "PANTENE")
        self.assertEqual(supera.capturar_marca("SH PLUSBELLE ANTIOXDANTE ARAND/OLEO X 1LT"), "PLUSBELLE")
        self.assertEqual(supera.capturar_marca("SH Pepe"), "?")
        self.assertEqual(supera.capturar_marca("SH PLUSBELLE BRILLO X 1000ML"), "PLUSBELLE")
        self.assertEqual(supera.capturar_marca("SH SEDAL CARBON ACTIVADO PEONIAS X340ML"), "SEDAL")
        self.assertEqual(supera.capturar_marca("SH SEDAL CERAMIDAS 340ML"), "SEDAL")
        self.assertEqual(supera.capturar_marca("SH SEDAL CERAMIDAS DOYP X300ML"), "SEDAL")
        self.assertEqual(supera.capturar_marca("SH SEDAL HIALURONICO Y VIT A X340ML"), "SEDAL")
        self.assertEqual(supera.capturar_marca("GASEOSA 7UP RETORNABLE X 2,25LT"), "7UP")
        self.assertEqual(supera.capturar_marca("GASEOSA COCA COLA X 500CC"), "COCA COLA")
        self.assertEqual(supera.capturar_marca("GASEOSA FANTA X 2,25LT"), "FANTA")
        self.assertEqual(supera.capturar_marca("GASEOSA MANAOS GRANADINA X 3LT"), "MANAOS")
        self.assertEqual(supera.capturar_marca("GASEOSA SPRITE X 500CC"), "SPRITE")
        self.assertEqual(supera.capturar_marca("GASEOSA PEPSI RETORNABLE X 2,25LT"), "PEPSI")
        self.assertEqual(supera.capturar_marca("GASEOSA SCHWEPPES TONICA X 1,5LT"), "SCHWEPPES")
        self.assertEqual(supera.capturar_marca("GASEOSA TALCA POMELO 3LT"), "TALCA")
        self.assertEqual(supera.capturar_marca("LECHE CHOC.ILOLAY KIDS X 1LT"), "ILOLAY")
        self.assertEqual(supera.capturar_marca("LECHE ILOLAY LV DESCREMADA X1LT"), "ILOLAY")
        self.assertEqual(supera.capturar_marca("LECHE LA SEREN.PARCIA.DESCR. LIV.2% 1 LT"), "LA SEREN.")
        self.assertEqual(supera.capturar_marca("LECHE LATTE ENTERA X 1 LT"), "LATTE")
        self.assertEqual(supera.capturar_marca("LECHE LS PARC. DESCREMADA ZERO LACTOSA 1L"), "LS")
        self.assertEqual(supera.capturar_marca("LECHE LS UAT BOTELLA PARC. DESCREMADA 1%"), "LS")
        self.assertEqual(supera.capturar_marca("LECHE LS SACHET ULTRA ENTERA 1 LT 3%"), "LS")
        self.assertEqual(supera.capturar_marca("LECHE LA SERENISIMA SACHET ULTRA DESCRE.1 LT"), "LA SERENISIMA")
        self.assertEqual(supera.capturar_marca("PAN LA ESPANOLA LACTAL BLANCO 380GR"), "LA ESPANOLA")
        self.assertEqual(supera.capturar_marca("PAN LA ESPANOLA LACTAL DOBLE SALVADO 580GR"), "LA ESPANOLA")
        self.assertEqual(supera.capturar_marca("PAN VENEZIANA LACTEADO FLIAR X 400G"), "VENEZIANA")
        self.assertEqual(supera.capturar_marca("PAN VENEZIANA MULTICERAL X410G"), "VENEZIANA")
        self.assertEqual(supera.capturar_marca("PAN VENEZIANA TRISALVADO X 360G"), "VENEZIANA")
        self.assertEqual(supera.capturar_marca("ARROZ EL GRANDE X 1 KG"), "EL GRANDE")
        self.assertEqual(supera.capturar_marca("ARROZ GALLO LARGO FINO PAQUETE X 500GR"), "GALLO")
        self.assertEqual(supera.capturar_marca("ARROZ GALLO RISOTTO PRIM 240GR"), "GALLO")
        self.assertEqual(supera.capturar_marca("ARROZ LUCCHETTI LARGO FINO PAQUETE X 500GR"), "LUCCHETTI")
        self.assertEqual(supera.capturar_marca("ARROZ TIO CARLOS LARGO FINO X 500GR"), "TIO CARLOS")
        self.assertEqual(supera.capturar_marca("ARROZ GALLO ORO PARBOIL X 500GR"), "GALLO")
        self.assertEqual(supera.capturar_marca("JABON DOVE KAR Y VAINILLA 90G"), "DOVE")
        self.assertEqual(supera.capturar_marca("JABON LUX LIRIO AZUL BOTANIC 3 X 125G"), "LUX")
        self.assertEqual(supera.capturar_marca("JABON PLUSBELLE FRESCURA NUTRIOIL 3X125GR"), "PLUSBELLE")
        self.assertEqual(supera.capturar_marca("JABON REXONA COTTON FRESH 125G"), "REXONA")
        self.assertEqual(supera.capturar_marca("JABON REXONA ANTIBACTERIAL ORIG.90GR"), "REXONA")
        self.assertEqual(supera.capturar_marca("JABON REXONA GLICERINA CITRUS X90G"), "REXONA")
        self.assertEqual(supera.capturar_marca("JABON REXONA ACTIVE MEN GLIC .HID 125G"), "REXONA")
        self.assertEqual(supera.capturar_marca("JABON REXONA ORCHID DERM X125G"), "REXONA")
        self.assertEqual(supera.capturar_marca("YERBA MATE PLAYADITO C/PALO SUAVE X1KG"), "PLAYADITO")
        self.assertEqual(supera.capturar_marca("YERBA MATE ROSAMONTE PLUS X500GR"), "ROSAMONTE")
        self.assertEqual(supera.capturar_marca("YERBA MATE TARAGUI FLEX S/PALO 1KG"), "TARAGUI")
        self.assertEqual(supera.capturar_marca("YERBA MATE YERBACID TRADICIONAL X500GR"), "YERBACID")
        self.assertEqual(supera.capturar_marca("YERBA MATE VERDEFLOR X1KG"), "VERDEFLOR")
        self.assertEqual(supera.capturar_marca("FIDEOS DON VICENTE TALLARIN X 500GR"), "DON VICENTE")
        self.assertEqual(supera.capturar_marca("FIDEOS LA PROVIDENCIA CODO X500GR"), "LA PROVIDENCIA")
        self.assertEqual(supera.capturar_marca("FIDEOS LUCCHETTI CABELLO ANGEL X 500GR"), "LUCCHETTI")
        self.assertEqual(supera.capturar_marca("FIDEOS LUCCHETTI MOSTACHOL N?51 X 500GR"), "LUCCHETTI")
        self.assertEqual(supera.capturar_marca("FIDEOS TERRABUSI DEDALITO 500GR"), "TERRABUSI")
        self.assertEqual(supera.capturar_marca("FIDEOS SAN AGUSTIN NIDO ANCHO X 500GR"), "SAN AGUSTIN")



    def test_descripcion(self):
        supera = SuperaPipeline()
        self.assertEqual(supera.capturar_descripcion("SH DOVE CUIDA Y PROTEGE X400ML"), "CUIDA Y PROTEGE")
        self.assertEqual(supera.capturar_descripcion("SH PANTENE HIDRATACION EXTREMA 200 ML"), "HIDRATACION EXTREMA")
        self.assertEqual(supera.capturar_descripcion("SH PLUSBELLE ANTIOXDANTE ARAND/OLEO X 1LT"), "ANTIOXDANTE ARAND/OLEO")
        self.assertEqual(supera.capturar_descripcion("SH PLUSBELLE BRILLO X 1000ML"), "BRILLO")
        self.assertEqual(supera.capturar_descripcion("SH SEDAL CARBON ACTIVADO PEONIAS X340ML"), "CARBON ACTIVADO PEONIAS")
        self.assertEqual(supera.capturar_descripcion("SH SEDAL CERAMIDAS 340ML"), "CERAMIDAS")
        self.assertEqual(supera.capturar_descripcion("SH SEDAL CERAMIDAS DOYP X300ML"), "CERAMIDAS DOYP")
        self.assertEqual(supera.capturar_descripcion("SH SEDAL HIALURONICO Y VIT A X340ML"), "HIALURONICO Y VIT A")
        self.assertEqual(supera.capturar_descripcion("GASEOSA 7UP RETORNABLE X 2,25LT"), "RETORNABLE")
        self.assertEqual(supera.capturar_descripcion("GASEOSA COCA COLA X 500CC"), "")
        self.assertEqual(supera.capturar_descripcion("GASEOSA FANTA X 2,25LT"), "")
        self.assertEqual(supera.capturar_descripcion("GASEOSA FANTA"), "?")
        self.assertEqual(supera.capturar_descripcion("GASEOSA MANAOS GRANADINA X 3LT"), "GRANADINA")
        self.assertEqual(supera.capturar_descripcion("GASEOSA SPRITE X 500CC"), "")
        self.assertEqual(supera.capturar_descripcion("GASEOSA PEPSI RETORNABLE X 2,25LT"), "RETORNABLE")
        self.assertEqual(supera.capturar_descripcion("GASEOSA SCHWEPPES TONICA X 1,5LT"), "TONICA")
        self.assertEqual(supera.capturar_descripcion("GASEOSA COCA COLA X 2.25LT"), "")
        self.assertEqual(supera.capturar_descripcion("LECHE CHOC.ILOLAY KIDS X 1LT"), "CHOC. KIDS")
        self.assertEqual(supera.capturar_descripcion("LECHE ILOLAY LV DESCREMADA X1LT"), "LV DESCREMADA")
        self.assertEqual(supera.capturar_descripcion("LECHE LA SEREN.PARCIA.DESCR. LIV.2% 1 LT"), "PARCIA.DESCR. LIV.2%")
        self.assertEqual(supera.capturar_descripcion("LECHE LATTE ENTERA X 1 LT"), "ENTERA")
        self.assertEqual(supera.capturar_descripcion("LECHE LS PARC. DESCREMADA ZERO LACTOSA 1L"), "PARC. DESCREMADA ZERO LACTOSA")
        self.assertEqual(supera.capturar_descripcion("LECHE LS UAT BOTELLA PARC. DESCREMADA 1%"), "PARC. DESCREMADA 1%")
        self.assertEqual(supera.capturar_descripcion("LECHE LS SACHET ULTRA ENTERA 1 LT 3%"), "SACHET ULTRA ENTERA 3%")
        self.assertEqual(supera.capturar_descripcion("LECHE LA SERENISIMA SACHET ULTRA DESCRE.1 LT"), "SACHET ULTRA DESCRE.")
        self.assertEqual(supera.capturar_descripcion("PAN LA ESPANOLA LACTAL BLANCO 380GR"), "LACTAL BLANCO")
        self.assertEqual(supera.capturar_descripcion("PAN LA ESPANOLA LACTAL DOBLE SALVADO 580GR"), "LACTAL DOBLE SALVADO")
        self.assertEqual(supera.capturar_descripcion("PAN VENEZIANA LACTEADO FLIAR X 400G"), "LACTEADO")
        self.assertEqual(supera.capturar_descripcion("PAN VENEZIANA MULTICERAL X410G"), "MULTICERAL")
        self.assertEqual(supera.capturar_descripcion("PAN VENEZIANA TRISALVADO X 360G"), "TRISALVADO")
        self.assertEqual(supera.capturar_descripcion("PAN LA ESPANOLA LACTAL DOLBLE SALVADO380GR"), "LACTAL DOLBLE SALVADO")
        self.assertEqual(supera.capturar_descripcion("ARROZ EL GRANDE X 1 KG"), "")
        self.assertEqual(supera.capturar_descripcion("ARROZ GALLO LARGO FINO PAQUETE X 500GR"), "LARGO FINO PAQUETE")
        self.assertEqual(supera.capturar_descripcion("ARROZ GALLO RISOTTO PRIM 240GR"), "RISOTTO PRIM")
        self.assertEqual(supera.capturar_descripcion("ARROZ LUCCHETTI LARGO FINO PAQUETE X 500GR"), "LARGO FINO PAQUETE")
        self.assertEqual(supera.capturar_descripcion("ARROZ TIO CARLOS LARGO FINO X 500GR"), "LARGO FINO")
        self.assertEqual(supera.capturar_descripcion("ARROZ GALLO ORO PARBOIL X 500GR"), "ORO PARBOIL")
        self.assertEqual(supera.capturar_descripcion("JABON DOVE KAR Y VAINILLA 90G"), "KAR Y VAINILLA")
        self.assertEqual(supera.capturar_descripcion("JABON LUX LIRIO AZUL BOTANIC 3 X 125G"), "LIRIO AZUL BOTANIC 3")
        self.assertEqual(supera.capturar_descripcion("JABON PLUSBELLE FRESCURA NUTRIOIL 3X125GR"), "FRESCURA NUTRIOIL 3")
        self.assertEqual(supera.capturar_descripcion("JABON REXONA COTTON FRESH 125G"), "COTTON FRESH")
        self.assertEqual(supera.capturar_descripcion("JABON REXONA ANTIBACTERIAL ORIG.90GR"), "ANTIBACTERIAL ORIG.")
        self.assertEqual(supera.capturar_descripcion("JABON REXONA GLICERINA CITRUS X90G"), "GLICERINA CITRUS")
        self.assertEqual(supera.capturar_descripcion("JABON REXONA ACTIVE MEN GLIC .HID 125G"), "ACTIVE MEN GLIC .HID")
        self.assertEqual(supera.capturar_descripcion("JABON REXONA ORCHID DERM X125G"), "ORCHID DERM")
        self.assertEqual(supera.capturar_descripcion("JABON DOVE BLANCO X 90GRS"), "BLANCO")
        self.assertEqual(supera.capturar_descripcion("YERBA MATE PLAYADITO C/PALO SUAVE X1KG"), "C/PALO SUAVE")
        self.assertEqual(supera.capturar_descripcion("YERBA MATE ROSAMONTE PLUS X500GR"), "PLUS")
        self.assertEqual(supera.capturar_descripcion("YERBA MATE TARAGUI FLEX S/PALO 1KG"), "FLEX S/PALO")
        self.assertEqual(supera.capturar_descripcion("YERBA MATE YERBACID TRADICIONAL X500GR"), "TRADICIONAL")
        self.assertEqual(supera.capturar_descripcion("YERBA MATE VERDEFLOR X1KG"), "")
        self.assertEqual(supera.capturar_descripcion("FIDEOS DON VICENTE TALLARIN X 500GR"), "TALLARIN")
        self.assertEqual(supera.capturar_descripcion("FIDEOS LA PROVIDENCIA CODO X500GR"), "CODO")
        self.assertEqual(supera.capturar_descripcion("FIDEOS LUCCHETTI CABELLO ANGEL X 500GR"), "CABELLO ANGEL")
        self.assertEqual(supera.capturar_descripcion("FIDEOS LUCCHETTI MOSTACHOL N?51 X 500GR"), "MOSTACHOL N?51")
        self.assertEqual(supera.capturar_descripcion("FIDEOS TERRABUSI DEDALITO 500GR"), "DEDALITO")
        self.assertEqual(supera.capturar_descripcion("FIDEOS SAN AGUSTIN NIDO ANCHO X 500GR"), "NIDO ANCHO")
        self.assertEqual(supera.capturar_descripcion("FIDEOS MATARAZZO TALLARIN  X 500GR"), "TALLARIN")
        
        
    def test_volumen(self):
        supera = SuperaPipeline()
        self.assertEqual(supera.capturar_volumen("SH DOVE CUIDA Y PROTEGE X400ML"), "400")
        self.assertEqual(supera.capturar_volumen("SH PANTENE HIDRATACION EXTREMA 200 ML"), "200")
        self.assertEqual(supera.capturar_volumen("SH PLUSBELLE ANTIOXDANTE ARAND/OLEO X 1LT"), "1000")
        self.assertEqual(supera.capturar_volumen("SH PLUSBELLE BRILLO X 1000ML"), "1000")
        self.assertEqual(supera.capturar_volumen("SH SEDAL CARBON ACTIVADO PEONIAS X340ML"), "340")
        self.assertEqual(supera.capturar_volumen("SH SEDAL CERAMIDAS 340ML"), "340")
        self.assertEqual(supera.capturar_volumen("SH SEDAL CERAMIDAS DOYP X300ML"), "300")
        self.assertEqual(supera.capturar_volumen("SH SEDAL HIALURONICO Y VIT A X340ML"), "340")
        self.assertEqual(supera.capturar_volumen("GASEOSA 7UP RETORNABLE X 2,25LT"), "2250")
        self.assertEqual(supera.capturar_volumen("GASEOSA COCA COLA X 500CC"), "500")
        self.assertEqual(supera.capturar_volumen("GASEOSA FANTA X 2,25LT"), "2250")
        self.assertEqual(supera.capturar_volumen("GASEOSA MANAOS GRANADINA X 3LT"), "3000")
        self.assertEqual(supera.capturar_volumen("GASEOSA SPRITE X 500CC"), "500")
        self.assertEqual(supera.capturar_volumen("GASEOSA PEPSI RETORNABLE X 2,25LT"), "2250")
        self.assertEqual(supera.capturar_volumen("GASEOSA SCHWEPPES TONICA X 1,5LT"), "1500")
        self.assertEqual(supera.capturar_volumen("GASEOSA COCA COLA X 2.25LT"), "2250")
        self.assertEqual(supera.capturar_volumen("LECHE CHOC.ILOLAY KIDS X 1LT"), "1000")
        self.assertEqual(supera.capturar_volumen("LECHE ILOLAY LV DESCREMADA X1LT"), "1000")
        self.assertEqual(supera.capturar_volumen("LECHE LA SEREN.PARCIA.DESCR. LIV.2% 1 LT"), "1000")
        self.assertEqual(supera.capturar_volumen("LECHE LATTE ENTERA X 1 LT"), "1000")
        self.assertEqual(supera.capturar_volumen("LECHE LS PARC. DESCREMADA ZERO LACTOSA 1L"), "1000")
        self.assertEqual(supera.capturar_volumen("LECHE LS UAT BOTELLA PARC. DESCREMADA 1%"), "1000")
        self.assertEqual(supera.capturar_volumen("LECHE LS SACHET ULTRA ENTERA 1 LT 3%"), "1000")
        self.assertEqual(supera.capturar_volumen("LECHE LA SERENISIMA SACHET ULTRA DESCRE.1 LT"), "1000")
        self.assertEqual(supera.capturar_volumen("PAN LA ESPANOLA LACTAL BLANCO 380GR"), "380")
        self.assertEqual(supera.capturar_volumen("PAN LA ESPANOLA LACTAL DOBLE SALVADO 580GR"), "580")
        self.assertEqual(supera.capturar_volumen("PAN VENEZIANA LACTEADO FLIAR X 400G"), "400")
        self.assertEqual(supera.capturar_volumen("PAN VENEZIANA MULTICERAL X410G"), "410")
        self.assertEqual(supera.capturar_volumen("PAN VENEZIANA TRISALVADO X 360G"), "360")
        self.assertEqual(supera.capturar_volumen("PAN LA ESPANOLA LACTAL DOLBLE SALVADO380GR"), "380")
        self.assertEqual(supera.capturar_volumen("ARROZ EL GRANDE X 1 KG"), "1000")
        self.assertEqual(supera.capturar_volumen("ARROZ GALLO LARGO FINO PAQUETE X 500GR"), "500")
        self.assertEqual(supera.capturar_volumen("ARROZ GALLO RISOTTO PRIM 240GR"), "240")
        self.assertEqual(supera.capturar_volumen("ARROZ LUCCHETTI LARGO FINO PAQUETE X 500GR"), "500")
        self.assertEqual(supera.capturar_volumen("ARROZ TIO CARLOS LARGO FINO X 500GR"), "500")
        self.assertEqual(supera.capturar_volumen("ARROZ GALLO ORO PARBOIL X 500GR"), "500")
        self.assertEqual(supera.capturar_volumen("JABON DOVE KAR Y VAINILLA 90G"), "90")
        self.assertEqual(supera.capturar_volumen("JABON LUX LIRIO AZUL BOTANIC 3 X 125G"), "125")
        self.assertEqual(supera.capturar_volumen("JABON PLUSBELLE FRESCURA NUTRIOIL 3X125GR"), "125")
        self.assertEqual(supera.capturar_volumen("JABON REXONA COTTON FRESH 125G"), "125")
        self.assertEqual(supera.capturar_volumen("JABON REXONA ANTIBACTERIAL ORIG.90GR"), "90")
        self.assertEqual(supera.capturar_volumen("JABON REXONA GLICERINA CITRUS X90G"), "90")
        self.assertEqual(supera.capturar_volumen("JABON REXONA ACTIVE MEN GLIC .HID 125G"), "125")
        self.assertEqual(supera.capturar_volumen("JABON REXONA ORCHID DERM X125G"), "125")
        self.assertEqual(supera.capturar_volumen("YERBA MATE PLAYADITO C/PALO SUAVE X1KG"), "1000")
        self.assertEqual(supera.capturar_volumen("YERBA MATE ROSAMONTE PLUS X500GR"), "500")
        self.assertEqual(supera.capturar_volumen("YERBA MATE TARAGUI FLEX S/PALO 1KG"), "1000")
        self.assertEqual(supera.capturar_volumen("YERBA MATE YERBACID TRADICIONAL X500GR"), "500")
        self.assertEqual(supera.capturar_volumen("YERBA MATE VERDEFLOR X1KG"), "1000")
        self.assertEqual(supera.capturar_volumen("FIDEOS DON VICENTE TALLARIN X 500GR"), "500")
        self.assertEqual(supera.capturar_volumen("FIDEOS LA PROVIDENCIA CODO X500GR"), "500")
        self.assertEqual(supera.capturar_volumen("FIDEOS LUCCHETTI CABELLO ANGEL X 500GR"), "500")
        self.assertEqual(supera.capturar_volumen("FIDEOS LUCCHETTI MOSTACHOL N?51 X 500GR"), "500")
        self.assertEqual(supera.capturar_volumen("FIDEOS TERRABUSI DEDALITO 500GR"), "500")
        self.assertEqual(supera.capturar_volumen("FIDEOS SAN AGUSTIN NIDO ANCHO X 500GR"), "500")


if __name__ == '__main__':
    unittest.main()
