import re
import unittest

from pipelines import SegalPipeline

class TestExpresionesRegulares(unittest.TestCase):
    def test_marca(self):
        segal = SegalPipeline()
        self.assertEqual(segal.capturar_marca("DOVE SHAMPOO 200ml HIDRATACIÓN INTENSA"), "DOVE")
        self.assertEqual(segal.capturar_marca("DOVE SHAMPOO 750ml RECONSTRUCCIÓN COMPLETA"), "DOVE")
        self.assertEqual(segal.capturar_marca("SEDAL SHAMPOO BOMBA ARGAN 190ml"), "SEDAL")
        self.assertEqual(segal.capturar_marca("SH Pepe"), "?")
        self.assertEqual(segal.capturar_marca("SEDAL SHAMPOO CERAMIDAS 300ml DOY PACK"), "SEDAL")
        self.assertEqual(segal.capturar_marca("SHAMPOO SEDAL BOMBA NUTRICIÓN 650ml"), "SEDAL")
        self.assertEqual(segal.capturar_marca("SHAMPOO SEDAL RIZOS DEFINIDOS 650ml"), "SEDAL")
        self.assertEqual(segal.capturar_marca("SHAMPOO SUAVE BRILLO CERAMIDAS 930ml"), "SUAVE")
        self.assertEqual(segal.capturar_marca("TRESEMMÉ SHAMPOO 200ml HIDRATACIÓN PROFUNDA"), "TRESEMMÉ")
        self.assertEqual(segal.capturar_marca("TRESEMMÉ SHAMPOO 750ml LISO KERATINA"), "TRESEMMÉ")
        self.assertEqual(segal.capturar_marca("COCA COLA ZERO 1.5Lts"), "COCA COLA")
        self.assertEqual(segal.capturar_marca("POWERADE FRUTOS TROPICALES ROJOS 500cc"), "POWERADE")
        self.assertEqual(segal.capturar_marca("FANTA NARANJA LATA 310cc"), "FANTA")
        self.assertEqual(segal.capturar_marca("PEPSI 2.25Lts"), "PEPSI")
        self.assertEqual(segal.capturar_marca("SPRITE LATA 310cc"), "SPRITE")
        self.assertEqual(segal.capturar_marca("SPRITE SIN AZUCAR 1.5Lts"), "SPRITE")
        self.assertEqual(segal.capturar_marca("MIRINDA DESCARTABLE 2.25Lts"), "MIRINDA")
        self.assertEqual(segal.capturar_marca("COCA COLA 500ml"), "COCA COLA")
        self.assertEqual(segal.capturar_marca("ARMONÍA LECHE 1L 1% DESCREMADA"), "ARMONÍA")
        self.assertEqual(segal.capturar_marca("LECHE 1% LA SERENÍSIMA 1Lt SACHET"), "LA SERENÍSIMA")
        self.assertEqual(segal.capturar_marca("LECHE CHOCOLATADA 1Lt TREGAR"), "TREGAR")
        self.assertEqual(segal.capturar_marca("LECHE CHOCOLATADA 200cc x 6u LA SERENÍSIMA"), "LA SERENÍSIMA")
        self.assertEqual(segal.capturar_marca("LECHE CHOCOLATADA CINDOR x 1L"), "CINDOR")
        self.assertEqual(segal.capturar_marca("LECHE DESCREMADA YOGURLAC 1Lt"), "YOGURLAC")
        self.assertEqual(segal.capturar_marca("LECHE DESCREMADA 1Lt TREGAR"), "TREGAR")
        self.assertEqual(segal.capturar_marca("LECHE DESCREMADA ILOLAY x 1 LT"), "ILOLAY")
        self.assertEqual(segal.capturar_marca("LECHE ENTERA YOGURLAC 1Lt"), "YOGURLAC")
        self.assertEqual(segal.capturar_marca("LECHE PET 0% LACTOSA LA SERENÍSIMA x 1L"), "LA SERENÍSIMA")
        self.assertEqual(segal.capturar_marca("PAN LACTAL VENEZIANA 400g"), "VENEZIANA")
        self.assertEqual(segal.capturar_marca("PAN MESA LACTAL 315g"), "LACTAL")
        self.assertEqual(segal.capturar_marca("PAN TIPO ARTESANO BIMBO 500g"), "BIMBO")
        self.assertEqual(segal.capturar_marca("PAN SALVADO LACTAL 560g"), "LACTAL")
        self.assertEqual(segal.capturar_marca("VENEZIANA PAN LACTAL INTEGRAL 630g"), "VENEZIANA")
        self.assertEqual(segal.capturar_marca("DON MARCOS ARROZ 1Kg LARGO FINO"), "DON MARCOS")
        self.assertEqual(segal.capturar_marca("DON MARCOS ARROZ 500g LARGO FINO"), "DON MARCOS")
        self.assertEqual(segal.capturar_marca("DON MARCOS ARROZ 1Kg PARBOIT"), "DON MARCOS")
        self.assertEqual(segal.capturar_marca("GALLO ARROZ 1Kg PARBOIL"), "GALLO")
        self.assertEqual(segal.capturar_marca("JABÓN ACTIVE REXONA 3u 125gr"), "REXONA")
        self.assertEqual(segal.capturar_marca("JABÓN ORQUÍDEA NEGRA LUX 3u 125gr"), "LUX")
        self.assertEqual(segal.capturar_marca("JABÓN SENSIBLE FRESH REXONA 3u 125gr"), "REXONA")
        self.assertEqual(segal.capturar_marca("JABÓN ROSAS FRANCESAS LUX 3u 125gr"), "LUX")
        self.assertEqual(segal.capturar_marca("JABÓN BAMBOO FRESH REXONA 3u 125gr"), "REXONA")
        self.assertEqual(segal.capturar_marca("JABÓN ORCHID FRESH REXONA 3u 125gr"), "REXONA")
        self.assertEqual(segal.capturar_marca("CRUZ DE MALTA SELECCIÓN 1Kg"), "CRUZ DE MALTA")
        self.assertEqual(segal.capturar_marca("MAÑANITA YERBA 500g BCP"), "MAÑANITA")
        self.assertEqual(segal.capturar_marca("TARAGUI YERBA 500g CON PALO"), "TARAGUI")
        self.assertEqual(segal.capturar_marca("VERDEFLOR YERBA 500g SERRANA"), "VERDEFLOR")
        self.assertEqual(segal.capturar_marca("UNIÓN YERBA 500g"), "UNIÓN")
        self.assertEqual(segal.capturar_marca("NOBLEZA GAUCHA SELECCIÓN 1kg"), "NOBLEZA GAUCHA")
        self.assertEqual(segal.capturar_marca("FIDEOS CODO LA PROVIDENCIA 500g"), "LA PROVIDENCIA")
        self.assertEqual(segal.capturar_marca("FIDEOS MOÑO LA PROVIDENCIA 500g"), "LA PROVIDENCIA")
        self.assertEqual(segal.capturar_marca("FIDEOS NIDO SPAGHETTI LA PROVIDENCIA 500g"), "LA PROVIDENCIA")
        self.assertEqual(segal.capturar_marca("FIDEOS MOSTACHOL MIX KNORR 500g"), "KNORR")
        self.assertEqual(segal.capturar_marca("KNORR FIDEOS CABELLO DE ÁNGEL 500g"), "KNORR")
        self.assertEqual(segal.capturar_marca("FIDEOS TIRABUZÓN KNORR 500g"), "KNORR")


    def test_descripcion(self):
        segal = SegalPipeline()
        self.assertEqual(segal.capturar_descripcion("DOVE SHAMPOO 200ml HIDRATACIÓN INTENSA"), "HIDRATACIÓN INTENSA")
        self.assertEqual(segal.capturar_descripcion("DOVE SHAMPOO 750ml RECONSTRUCCIÓN COMPLETA"), "RECONSTRUCCIÓN COMPLETA")
        self.assertEqual(segal.capturar_descripcion("SEDAL SHAMPOO BOMBA ARGAN 190ml"), "BOMBA ARGAN")
        self.assertEqual(segal.capturar_descripcion("SEDAL SHAMPOO CERAMIDAS 300ml DOY PACK"), "CERAMIDAS DOY PACK")
        self.assertEqual(segal.capturar_descripcion("SHAMPOO SEDAL BOMBA NUTRICIÓN 650ml"), "BOMBA NUTRICIÓN")
        self.assertEqual(segal.capturar_descripcion("SEDAL SHAMPOO CERAMIDAS 650ml"), "CERAMIDAS") 
        self.assertEqual(segal.capturar_descripcion("SHAMPOO SEDAL RIZOS DEFINIDOS 650ml"), "RIZOS DEFINIDOS")
        self.assertEqual(segal.capturar_descripcion("SHAMPOO SUAVE BRILLO CERAMIDAS 930ml"), "BRILLO CERAMIDAS")
        self.assertEqual(segal.capturar_descripcion("TRESEMMÉ SHAMPOO 200ml HIDRATACIÓN PROFUNDA"), "HIDRATACIÓN PROFUNDA")
        self.assertEqual(segal.capturar_descripcion("TRESEMMÉ SHAMPOO 750ml LISO KERATINA"), "LISO KERATINA")
        self.assertEqual(segal.capturar_descripcion("COCA COLA ZERO 1.5Lts"), "ZERO")
        self.assertEqual(segal.capturar_descripcion("POWERADE FRUTOS TROPICALES ROJOS 500cc"), "FRUTOS TROPICALES ROJOS")
        self.assertEqual(segal.capturar_descripcion("FANTA NARANJA LATA 310cc"), "NARANJA LATA")
        self.assertEqual(segal.capturar_descripcion("PEPSI 2.25Lts"), "")
        self.assertEqual(segal.capturar_descripcion("PEPSI"), "?")
        self.assertEqual(segal.capturar_descripcion("7UP 2.25Lts"), "")
        self.assertEqual(segal.capturar_descripcion("SPRITE LATA 310cc"), "LATA")
        self.assertEqual(segal.capturar_descripcion("SPRITE SIN AZUCAR 1.5Lts"), "SIN AZUCAR")
        self.assertEqual(segal.capturar_descripcion("MIRINDA DESCARTABLE 2.25Lts"), "DESCARTABLE")
        self.assertEqual(segal.capturar_descripcion("COCA COLA 500ml"), "")
        self.assertEqual(segal.capturar_descripcion("ARMONÍA LECHE 1L 1% DESCREMADA"), "1% DESCREMADA")
        self.assertEqual(segal.capturar_descripcion("LECHE 1% LA SERENÍSIMA 1Lt SACHET"), "1% SACHET")
        self.assertEqual(segal.capturar_descripcion("LECHE CHOCOLATADA 1Lt TREGAR"), "CHOCOLATADA")
        self.assertEqual(segal.capturar_descripcion("LECHE CHOCOLATADA 200cc x 6u LA SERENÍSIMA"), "CHOCOLATADA x 6u")
        self.assertEqual(segal.capturar_descripcion("LECHE CHOCOLATADA CINDOR x 1L"), "CHOCOLATADA")
        self.assertEqual(segal.capturar_descripcion("LECHE DESCREMADA YOGURLAC 1Lt"), "DESCREMADA")
        self.assertEqual(segal.capturar_descripcion("LECHE DESCREMADA 1Lt TREGAR"), "DESCREMADA")
        self.assertEqual(segal.capturar_descripcion("LECHE DESCREMADA ILOLAY x 1 LT"), "DESCREMADA")
        self.assertEqual(segal.capturar_descripcion("LECHE ENTERA YOGURLAC 1Lt"), "ENTERA")
        self.assertEqual(segal.capturar_descripcion("LECHE PET 0% LACTOSA LA SERENÍSIMA x 1L"), "0% LACTOSA")
        self.assertEqual(segal.capturar_descripcion("PAN LACTAL VENEZIANA 400g"), "LACTAL")
        self.assertEqual(segal.capturar_descripcion("PAN MESA LACTAL 315g"), "MESA")
        self.assertEqual(segal.capturar_descripcion("PAN TIPO ARTESANO BIMBO 500g"), "TIPO ARTESANO")
        self.assertEqual(segal.capturar_descripcion("PAN SALVADO LACTAL 560g"), "SALVADO")
        self.assertEqual(segal.capturar_descripcion("VENEZIANA PAN LACTAL INTEGRAL 630g"), "LACTAL INTEGRAL")
        self.assertEqual(segal.capturar_descripcion("DON MARCOS ARROZ 1Kg LARGO FINO"), "LARGO FINO")
        self.assertEqual(segal.capturar_descripcion("DON MARCOS ARROZ 500g LARGO FINO"), "LARGO FINO")
        self.assertEqual(segal.capturar_descripcion("DON MARCOS ARROZ 1Kg PARBOIT"), "PARBOIT")
        self.assertEqual(segal.capturar_descripcion("GALLO ARROZ 1Kg PARBOIL"), "PARBOIL")
        self.assertEqual(segal.capturar_descripcion("GALLO ARROZ 1Kg LARGO FINO"), "LARGO FINO")
        self.assertEqual(segal.capturar_descripcion("MAXIMO ARROZ 1Kg LARGO FINO"), "LARGO FINO")
        self.assertEqual(segal.capturar_descripcion("PERSEGUIDO ARROZ 1Kg LARGO FINO"), "LARGO FINO")
        self.assertEqual(segal.capturar_descripcion("JABÓN ACTIVE REXONA 3u 125gr"), "ACTIVE 3u")
        self.assertEqual(segal.capturar_descripcion("JABÓN ORQUÍDEA NEGRA LUX 3u 125gr"), "ORQUÍDEA NEGRA 3u")
        self.assertEqual(segal.capturar_descripcion("JABÓN SENSIBLE FRESH REXONA 3u 125gr"), "SENSIBLE FRESH 3u")
        self.assertEqual(segal.capturar_descripcion("JABÓN ROSAS FRANCESAS LUX 3u 125gr"), "ROSAS FRANCESAS 3u")
        self.assertEqual(segal.capturar_descripcion("JABÓN BAMBOO FRESH REXONA 3u 125gr"), "BAMBOO FRESH 3u")
        self.assertEqual(segal.capturar_descripcion("JABÓN ORCHID FRESH REXONA 3u 125gr"), "ORCHID FRESH 3u")
        self.assertEqual(segal.capturar_descripcion("CRUZ DE MALTA SELECCIÓN 1Kg"), "SELECCIÓN")
        self.assertEqual(segal.capturar_descripcion("MAÑANITA YERBA 500g BCP"), "BCP")
        self.assertEqual(segal.capturar_descripcion("TARAGUI YERBA 500g CON PALO"), "CON PALO")
        self.assertEqual(segal.capturar_descripcion("VERDEFLOR YERBA 500g SERRANA"), "SERRANA")
        self.assertEqual(segal.capturar_descripcion("UNIÓN YERBA 500g"), "")
        self.assertEqual(segal.capturar_descripcion("CHAMIGO YERBA 500g"), "")
        self.assertEqual(segal.capturar_descripcion("YERBA BUENAS Y SANTAS 500g"), "")
        self.assertEqual(segal.capturar_descripcion("NOBLEZA GAUCHA SELECCIÓN 1kg"), "SELECCIÓN")  
        self.assertEqual(segal.capturar_descripcion("FIDEOS CODO LA PROVIDENCIA 500g"), "CODO")
        self.assertEqual(segal.capturar_descripcion("FIDEOS MOÑO LA PROVIDENCIA 500g"), "MOÑO")
        self.assertEqual(segal.capturar_descripcion("FIDEOS NIDO SPAGHETTI LA PROVIDENCIA 500g"), "NIDO SPAGHETTI")
        self.assertEqual(segal.capturar_descripcion("FIDEOS MOSTACHOL MIX KNORR 500g"), "MOSTACHOL MIX")
        self.assertEqual(segal.capturar_descripcion("SPAGHETTI DON FELIPE 500gr"), "SPAGHETTI")
        self.assertEqual(segal.capturar_descripcion("TALLARINES DON FELIPE 500g"), "TALLARINES")
        self.assertEqual(segal.capturar_descripcion("KNORR FIDEOS CABELLO DE ÁNGEL 500g"), "CABELLO DE ÁNGEL")
        self.assertEqual(segal.capturar_descripcion("FIDEOS TIRABUZÓN KNORR 500g"), "TIRABUZÓN")
        self.assertEqual(segal.capturar_descripcion("FIDEOS DEDALITO PROVIDENCIA 500gr"), "DEDALITO")  
        self.assertEqual(segal.capturar_descripcion("FIDEOS MUNICIÓN PROVIDENCIA 500gr"), "MUNICIÓN")  


    def test_volumen(self):
        segal = SegalPipeline()
        self.assertEqual(segal.capturar_volumen("DOVE SHAMPOO 200ml HIDRATACIÓN INTENSA"), "200")
        self.assertEqual(segal.capturar_volumen("DOVE SHAMPOO 750ml RECONSTRUCCIÓN COMPLETA"), "750")
        self.assertEqual(segal.capturar_volumen("SEDAL SHAMPOO BOMBA ARGAN 190ml"), "190")
        self.assertEqual(segal.capturar_volumen("SEDAL SHAMPOO CERAMIDAS 300ml DOY PACK"), "300")
        self.assertEqual(segal.capturar_volumen("SHAMPOO SEDAL BOMBA NUTRICIÓN 650ml"), "650")
        self.assertEqual(segal.capturar_volumen("SHAMPOO SEDAL RIZOS DEFINIDOS 650ml"), "650")
        self.assertEqual(segal.capturar_volumen("SHAMPOO SUAVE BRILLO CERAMIDAS 930ml"), "930")
        self.assertEqual(segal.capturar_volumen("TRESEMMÉ SHAMPOO 200ml HIDRATACIÓN PROFUNDA"), "200")
        self.assertEqual(segal.capturar_volumen("TRESEMMÉ SHAMPOO 750ml LISO KERATINA"), "750")
        self.assertEqual(segal.capturar_volumen("COCA COLA ZERO 1.5Lts"), "1500")
        self.assertEqual(segal.capturar_volumen("POWERADE FRUTOS TROPICALES ROJOS 500cc"), "500")
        self.assertEqual(segal.capturar_volumen("FANTA NARANJA LATA 310cc"), "310")
        self.assertEqual(segal.capturar_volumen("PEPSI 2.25Lts"), "2250")
        self.assertEqual(segal.capturar_volumen("SPRITE LATA 310cc"), "310")
        self.assertEqual(segal.capturar_volumen("SPRITE SIN AZUCAR 1.5Lts"), "1500")
        self.assertEqual(segal.capturar_volumen("MIRINDA DESCARTABLE 2.25Lts"), "2250")
        self.assertEqual(segal.capturar_volumen("COCA COLA 500ml"), "500")
        self.assertEqual(segal.capturar_volumen("ARMONÍA LECHE 1L 1% DESCREMADA"), "1000")
        self.assertEqual(segal.capturar_volumen("LECHE 1% LA SERENÍSIMA 1Lt SACHET"), "1000")
        self.assertEqual(segal.capturar_volumen("LECHE CHOCOLATADA 1Lt TREGAR"), "1000")
        self.assertEqual(segal.capturar_volumen("LECHE CHOCOLATADA 200cc x 6u LA SERENÍSIMA"), "200")
        self.assertEqual(segal.capturar_volumen("LECHE CHOCOLATADA CINDOR x 1L"), "1000")
        self.assertEqual(segal.capturar_volumen("LECHE DESCREMADA YOGURLAC 1Lt"), "1000")
        self.assertEqual(segal.capturar_volumen("LECHE DESCREMADA 1Lt TREGAR"), "1000")
        self.assertEqual(segal.capturar_volumen("LECHE DESCREMADA ILOLAY x 1 LT"), "1000")
        self.assertEqual(segal.capturar_volumen("LECHE ENTERA YOGURLAC 1Lt"), "1000")
        self.assertEqual(segal.capturar_volumen("LECHE PET 0% LACTOSA LA SERENÍSIMA x 1L"), "1000")
        self.assertEqual(segal.capturar_volumen("LECHE CHOCOLATADA LA SERENÍSIMA"), "1000")
        self.assertEqual(segal.capturar_volumen("PAN LACTAL VENEZIANA 400g"), "400")
        self.assertEqual(segal.capturar_volumen("PAN MESA LACTAL 315g"), "315")
        self.assertEqual(segal.capturar_volumen("PAN TIPO ARTESANO BIMBO 500g"), "500")
        self.assertEqual(segal.capturar_volumen("PAN SALVADO LACTAL 560g"), "560")
        self.assertEqual(segal.capturar_volumen("VENEZIANA PAN LACTAL INTEGRAL 630g"), "630")
        self.assertEqual(segal.capturar_volumen("DON MARCOS ARROZ 1Kg LARGO FINO"), "1000")
        self.assertEqual(segal.capturar_volumen("DON MARCOS ARROZ 500g LARGO FINO"), "500")
        self.assertEqual(segal.capturar_volumen("DON MARCOS ARROZ 1Kg PARBOIT"), "1000")
        self.assertEqual(segal.capturar_volumen("GALLO ARROZ 1Kg PARBOIL"), "1000")
        self.assertEqual(segal.capturar_volumen("GALLO ARROZ 1Kg LARGO FINO"), "1000")
        self.assertEqual(segal.capturar_volumen("CRUZ DE MALTA SELECCIÓN 1Kg"), "1000")
        self.assertEqual(segal.capturar_volumen("MAÑANITA YERBA 500g BCP"), "500")
        self.assertEqual(segal.capturar_volumen("TARAGUI YERBA 500g CON PALO"), "500")
        self.assertEqual(segal.capturar_volumen("VERDEFLOR YERBA 500g SERRANA"), "500")
        self.assertEqual(segal.capturar_volumen("UNIÓN YERBA 500g"), "500")
        self.assertEqual(segal.capturar_volumen("NOBLEZA GAUCHA SELECCIÓN 1kg"), "1000") 
        self.assertEqual(segal.capturar_volumen("FIDEOS CODO LA PROVIDENCIA 500g"), "500")
        self.assertEqual(segal.capturar_volumen("FIDEOS MOÑO LA PROVIDENCIA 500g"), "500")
        self.assertEqual(segal.capturar_volumen("FIDEOS NIDO SPAGHETTI LA PROVIDENCIA 500g"), "500")
        self.assertEqual(segal.capturar_volumen("FIDEOS MOSTACHOL MIX KNORR 500g"), "500")
        self.assertEqual(segal.capturar_volumen("KNORR FIDEOS CABELLO DE ÁNGEL 500g"), "500")
        self.assertEqual(segal.capturar_volumen("FIDEOS TIRABUZÓN KNORR 500g"), "500")

        self.assertEqual(segal.capturar_volumen("JABÓN ACTIVE REXONA 3u 125gr"), "375")
        self.assertEqual(segal.capturar_volumen("JABÓN ORQUÍDEA NEGRA LUX 3u 125gr"), "375")
        self.assertEqual(segal.capturar_volumen("JABÓN SENSIBLE FRESH REXONA 3u 125gr"), "375")
        self.assertEqual(segal.capturar_volumen("JABÓN ROSAS FRANCESAS LUX 3u 125gr"), "375")
        self.assertEqual(segal.capturar_volumen("JABÓN BAMBOO FRESH REXONA 3u 125gr"), "375")
        self.assertEqual(segal.capturar_volumen("JABÓN ORCHID FRESH REXONA 3u 125gr"), "375")
        self.assertEqual(segal.capturar_volumen("JABÓN ACTIVE REXONA 3u 125gr"), "375")
        self.assertEqual(segal.capturar_volumen("JABÓN BAMBOO FRESH REXONA 3u 125gr"), "375")
        self.assertEqual(segal.capturar_volumen("JABÓN COTTON REXONA 3u 125gr"), "375")
        self.assertEqual(segal.capturar_volumen("JABÓN FLOR VAINILLA LUX 3u 120gr"), "360")
        self.assertEqual(segal.capturar_volumen("JABÓN JAZMÍN LUX 3u 120gr"), "360")
        self.assertEqual(segal.capturar_volumen("JABÓN LIRIO AZUL LUX 3u 120gr"), "360")
        self.assertEqual(segal.capturar_volumen("JABÓN ORCHID FRESH REXONA 3u 125gr"), "375")
        self.assertEqual(segal.capturar_volumen("JABÓN ORQUÍDEA NEGRA LUX 3u 120gr"), "360")
        self.assertEqual(segal.capturar_volumen("JABÓN ROSAS FRANCESAS LUX 3u 120gr"), "360")
        self.assertEqual(segal.capturar_volumen("JABÓN SENSIBLE FRESH REXONA 3u 125gr"), "375")
        self.assertEqual(segal.capturar_volumen("FIDEOS DEDALITO PROVIDENCIA 500gr"), "500")
        self.assertEqual(segal.capturar_volumen("FIDEOS MUNICIÓN PROVIDENCIA 500gr"), "500")





if __name__ == '__main__':
    unittest.main()
