name: Build and Push CronJob Image

on:
  push:
    paths:
      - 'CronJob/**'
      - '.github/workflows/cronjob.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./CronJob
          file: ./CronJob/Dockerfile
          push: true
          tags: martingreyes/tif-cronjob:latest
          platforms: linux/amd64,linux/arm64
