# name: Build and Push Frontend Image

# on:
#   push:
#     paths:
#       - 'Frontend/**'
#       - '.github/workflows/frontend.yml'

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and push image
#         uses: docker/build-push-action@v5
#         with:
#           context: ./Frontend
#           file: ./Frontend/Dockerfile
#           push: true
#           tags: martingreyes/tif-frontend:latest
#           platforms: linux/amd64,linux/arm64

