name: Build and Push WebScraping Image

on:
  push:
    paths:
      - 'WebScraping/**'
      - '.github/workflows/webscraping.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./WebScraping
          file: ./WebScraping/Dockerfile
          push: true
          tags: martingreyes/tif-webscraping:latest
